Updating OAuth 2.0 documentation
slingr-stack/slingr-docs pull request #143
Opened 2024-11-07 17:31 UTC by jsanchez-slingr

## Summary

This pull request updates the documentation for the Single Sign-On (SSO) feature for OAuth. Key changes include:

- Replacing instances of "URI" with "URL" throughout the documentation.
- Splitting the user processing script for better clarity and standardization.
- Introducing two methods for access token retrieval:
    Access Token Retrieval Method: Choose between "URL" or "Script".
    Access Token URL: A static endpoint from which the access token is retrieved.
    Access Token Script: Custom code for access token retrieval.

- Updating the "User Mapping Script" section to provide a more standard example.
- The "Access Token Script" documentation now references the HTTP package or service.
- The documentation will refer to the process as "OAuth 2.0"

## Motivation

These updates aim to clarify the access token retrieval process and improve the overall usability of the documentation. By standardizing examples and methods, we support a wider range of use cases and enhance user understanding, leading to more effective implementation of the SSO feature.

## Checks

- [ ] Read [Create a Pull Request](https://getdoks.org/docs/contributing/how-to-contribute/#create-a-pull-request)
- [ ] Supports all screen sizes (if relevant)
- [ ] Supports both light and dark mode (if relevant)
- [ ] Passes `npm run test`

2024-11-07 17:41 UTC, pasaperez-slingr commented
/describe

2024-11-07 17:43 UTC, pasaperez-slingr commented
/review

2024-11-07 17:45 UTC, pasaperez-slingr commented
/improve

2024-11-07 17:55 UTC, pasaperez-slingr requested changes

2024-11-07 17:55 UTC, pasaperez-slingr commented on content/en/dev-reference/security/single-sign-on.md
> +    const accessTokenResponse = svc.http.post({
Here let's use the package
```suggestion
    const accessTokenResponse = pkg.http.post({
```

2024-11-07 17:55 UTC, pasaperez-slingr commented on content/en/dev-reference/security/single-sign-on.md
> +  const userDataResponse = svc.http.get({
```suggestion
  const userDataResponse = pkg.http.get({
```

2024-11-09 02:02 UTC, sebasmoyano commented
#approve

2024-12-02 20:47 UTC, merged

2024-12-02 20:48 UTC, pasaperez-slingr commented
Looks good, thanks Joaquín!